packages:
    - 'apps/*'
    - 'packages/*'

supportedArchitectures:
    os:
        - win32
        - linux
        - darwin
    cpu:
        - x64
        - arm64

ignoredBuiltDependencies:
    - '@ffmpeg-installer/darwin-arm64'
    - '@ffmpeg-installer/darwin-x64'
    - '@ffmpeg-installer/linux-arm64'
    - '@ffmpeg-installer/linux-x64'
    - '@ffmpeg-installer/win32-x64'

onlyBuiltDependencies:
    - '@parcel/watcher'
    - '@prisma/client'
    - '@prisma/engines'
    - argon2
    - esbuild
    - prisma
    - sharp
    - bufferutil
    - utf-8-validate
    - protobufjs
