export const fileTypes = [
    {
        label: 'Plain Text',
        hljs: 'plaintext',
        mime: 'text/plain',
        extension: 'txt',
    },
    {
        label: 'Markdown',
        hljs: 'markdown',
        mime: 'text/markdown',
        extension: 'md',
    },
    {
        label: 'HTML',
        hljs: 'html',
        mime: 'text/html',
        extension: 'html',
    },
    {
        label: 'CSS',
        hljs: 'css',
        mime: 'text/css',
        extension: 'css',
    },
    {
        label: 'SCSS',
        hljs: 'scss',
        mime: 'text/x-scss',
        extension: 'scss',
    },
    {
        label: 'LESS',
        hljs: 'less',
        mime: 'text/x-less',
        extension: 'less',
    },
    {
        label: 'JavaScript',
        hljs: 'javascript',
        mime: 'application/javascript',
        extension: 'js',
    },
    {
        label: 'TypeScript',
        hljs: 'typescript',
        mime: 'application/typescript',
        extension: 'ts',
    },
    {
        label: 'JSON',
        hljs: 'json',
        mime: 'application/json',
        extension: 'json',
    },
    {
        label: 'YAML',
        hljs: 'yaml',
        mime: 'text/yaml',
        extension: 'yml',
    },
    {
        label: 'Python',
        hljs: 'python',
        mime: 'text/x-python',
        extension: 'py',
    },
    {
        label: 'Java',
        hljs: 'java',
        mime: 'text/x-java',
        extension: 'java',
    },
    {
        label: 'C',
        hljs: 'c',
        mime: 'text/x-csrc',
        extension: 'c',
    },
    {
        label: 'C++',
        hljs: 'cpp',
        mime: 'text/x-c++src',
        extension: 'cpp',
    },
    {
        label: 'C#',
        hljs: 'csharp',
        mime: 'text/x-csharp',
        extension: 'cs',
    },
    {
        label: 'Go',
        hljs: 'go',
        mime: 'text/x-go',
        extension: 'go',
    },
    {
        label: 'Ruby',
        hljs: 'ruby',
        mime: 'text/x-ruby',
        extension: 'rb',
    },
    {
        label: 'PHP',
        hljs: 'php',
        mime: 'application/x-php',
        extension: 'php',
    },
    {
        label: 'Swift',
        hljs: 'swift',
        mime: 'text/x-swift',
        extension: 'swift',
    },
    {
        label: 'Kotlin',
        hljs: 'kotlin',
        mime: 'text/x-kotlin',
        extension: 'kt',
    },
    {
        label: 'Rust',
        hljs: 'rust',
        mime: 'text/x-rustsrc',
        extension: 'rs',
    },
    {
        label: 'Perl',
        hljs: 'perl',
        mime: 'text/x-perl',
        extension: 'pl',
    },
    {
        label: 'Lua',
        hljs: 'lua',
        mime: 'text/x-lua',
        extension: 'lua',
    },
    {
        label: 'Bash',
        hljs: 'sh',
        mime: 'application/x-sh',
        extension: 'sh',
    },
    {
        label: 'R',
        hljs: 'r',
        mime: 'text/x-r',
        extension: 'r',
    },
    {
        label: 'SQL',
        hljs: 'sql',
        mime: 'text/x-sql',
        extension: 'sql',
    },
    {
        label: 'XML',
        hljs: 'xml',
        mime: 'application/xml',
        extension: 'xml',
    },
    {
        label: 'Elixir',
        hljs: 'elixir',
        mime: 'text/x-elixir',
        extension: 'ex',
    },
];
